export default function Favicons(): JSX.Element {
	return (
		<>
			<link rel="icon" href="/favicon.ico" sizes="any" />
			<link
				rel="apple-touch-icon"
				href="/apple-touch-icon.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="57x57"
				href="/apple-touch-icon-57x57.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="72x72"
				href="/apple-touch-icon-72x72.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="76x76"
				href="/apple-touch-icon-76x76.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="114x114"
				href="/apple-touch-icon-114x114.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="120x120"
				href="/apple-touch-icon-120x120.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="144x144"
				href="/apple-touch-icon-144x144.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="152x152"
				href="/apple-touch-icon-152x152.png"
				type="image/png"
			/>
			<link
				rel="apple-touch-icon"
				sizes="180x180"
				href="/apple-touch-icon-180x180.png"
				type="image/png"
			/>
		</>
	);
}
